### ISSUE TITLE
[Exploratory] Find acceptable storage solution for tracked games

### ISSUE THREAD

**Issue by AnnaThorne** [Effie2096/BackTrack#5]
Find a proper storage solution for the backlog.
Fallback to sqlite if nothing comes to mind.

**Comment by FaithfulFox** [comment]
[nitrite java](https://github.com/nitrite/nitrite-java)
[potassium nitrite](https://github.com/nitrite/nitrite-java/tree/main/potassium-nitrite)
[kotlin sdk](https://nitrite.dizitart.com/kotlin-sdk/getting-started/index.html)
- desktop, android and iOS support (ebic)

will be sufficient for the client app but may look into using serverside database for the Vault in the future with translation between the two if needed.

**Comment by AnnaThorne** [comment]
> [nitrite java](https://github.com/nitrite/nitrite-java)
> [potassium nitrite](https://github.com/nitrite/nitrite-java/tree/main/potassium-nitrite)
> [kotlin sdk](https://nitrite.dizitart.com/kotlin-sdk/getting-started/index.html)
> - desktop, android and iOS support (ebic)
> 
> will be sufficient for the client app but may look into using serverside database for the Vault in the future with translation between the two if needed.

based so proud of you bestie
